// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebApi.Shared.Infrastructure;
using WebApi.Surveys.Domain.Entities;

#nullable disable

namespace Shared.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WebApi.Companies.Domain.Entities.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("slug");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_companies");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_companies_slug");

                    b.ToTable("companies", (string)null);
                });

            modelBuilder.Entity("WebApi.Customers.Domain.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<string>("Contact")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("contact");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cpf");

                    b.Property<int>("FidelityPoints")
                        .HasColumnType("integer")
                        .HasColumnName("fidelity_points");

                    b.Property<DateTime?>("LastFeedbackDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_feedback_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<int>("TotalFeedbacks")
                        .HasColumnType("integer")
                        .HasColumnName("total_feedbacks");

                    b.HasKey("Id")
                        .HasName("pk_customers");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("ix_customers_company_id");

                    b.ToTable("customers", (string)null);
                });

            modelBuilder.Entity("WebApi.Surveys.Domain.Entities.Survey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default");

                    b.Property<string>("Metadata")
                        .HasColumnType("text")
                        .HasColumnName("metadata");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_surveys");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("ix_surveys_company_id");

                    b.ToTable("surveys", (string)null);
                });

            modelBuilder.Entity("WebApi.Surveys.Domain.Entities.SurveyAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<string>("ExtraComment")
                        .HasColumnType("text")
                        .HasColumnName("extra_comment");

                    b.Property<int?>("NumericValue")
                        .HasColumnType("integer")
                        .HasColumnName("numeric_value");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid")
                        .HasColumnName("question_id");

                    b.Property<Guid>("SurveyId")
                        .HasColumnType("uuid")
                        .HasColumnName("survey_id");

                    b.Property<string>("TextValue")
                        .HasColumnType("text")
                        .HasColumnName("text_value");

                    b.HasKey("Id")
                        .HasName("pk_survey_answers");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_survey_answers_customer_id");

                    b.HasIndex("QuestionId")
                        .HasDatabaseName("ix_survey_answers_question_id");

                    b.HasIndex("SurveyId", "CreatedAt")
                        .HasDatabaseName("ix_survey_answers_survey_id_created_at");

                    b.ToTable("survey_answers", (string)null);
                });

            modelBuilder.Entity("WebApi.Surveys.Domain.Entities.SurveyQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AllowComment")
                        .HasColumnType("boolean")
                        .HasColumnName("allow_comment");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("is_required");

                    b.Property<List<SurveyQuestionMetadata>>("Metadata")
                        .HasColumnType("json")
                        .HasColumnName("metadata");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<Guid>("SurveyId")
                        .HasColumnType("uuid")
                        .HasColumnName("survey_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("title");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_survey_questions");

                    b.HasIndex("SurveyId")
                        .HasDatabaseName("ix_survey_questions_survey_id");

                    b.ToTable("survey_questions", (string)null);
                });

            modelBuilder.Entity("WebApi.Customers.Domain.Entities.Customer", b =>
                {
                    b.HasOne("WebApi.Companies.Domain.Entities.Company", "Company")
                        .WithMany("Customers")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_customers_companies_company_id");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("WebApi.Surveys.Domain.Entities.Survey", b =>
                {
                    b.HasOne("WebApi.Companies.Domain.Entities.Company", "Company")
                        .WithMany("Surveys")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_surveys_companies_company_id");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("WebApi.Surveys.Domain.Entities.SurveyAnswer", b =>
                {
                    b.HasOne("WebApi.Customers.Domain.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .HasConstraintName("fk_survey_answers_customers_customer_id");

                    b.HasOne("WebApi.Surveys.Domain.Entities.SurveyQuestion", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_survey_answers_survey_questions_question_id");

                    b.HasOne("WebApi.Surveys.Domain.Entities.Survey", "Survey")
                        .WithMany()
                        .HasForeignKey("SurveyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_survey_answers_surveys_survey_id");

                    b.Navigation("Customer");

                    b.Navigation("Question");

                    b.Navigation("Survey");
                });

            modelBuilder.Entity("WebApi.Surveys.Domain.Entities.SurveyQuestion", b =>
                {
                    b.HasOne("WebApi.Surveys.Domain.Entities.Survey", "Survey")
                        .WithMany("Questions")
                        .HasForeignKey("SurveyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_survey_questions_surveys_survey_id");

                    b.Navigation("Survey");
                });

            modelBuilder.Entity("WebApi.Companies.Domain.Entities.Company", b =>
                {
                    b.Navigation("Customers");

                    b.Navigation("Surveys");
                });

            modelBuilder.Entity("WebApi.Surveys.Domain.Entities.Survey", b =>
                {
                    b.Navigation("Questions");
                });
#pragma warning restore 612, 618
        }
    }
}
